default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4
  host: db

development:
  <<: *default
  username: root
  password: "password"
  database: todo_app_development

test:
  <<: *default
  username: root
  password: "password"
  database: todo_app_test
